#!/bin/bash

if [ "$1" = "--debug" ]; then
  echo "Running perl6 script in debug mode..."
  EXEC=perl6-gdb-m
  shift
elif [ "$1" = "--valgrind" ]; then
  echo "Running perl6 script in valgrind mode..."
  EXEC=perl6-valgrind-m
  shift
elif [ "$1" = "--pbuild" ]; then
  PARALLEL_BUILD=1
  EXEC=perl6
  shift
else
  #echo "Running perl6 script..."
  EXEC=perl6
fi

INCLUDES="\
-I${P6_GTK_HOME}/Method-Also/lib  \
-I${P6_GTK_HOME}/p6-ICal/lib      \
-I${P6_GTK_HOME}/p6-GLib/lib      \
-I${P6_GTK_HOME}/p6-ICal-GLib/lib \
-I${P6_GTK_HOME}/p6-ATK/lib       \
-I${P6_GTK_HOME}/p6-JSON-GLib/lib \
-I${P6_GTK_HOME}/p6-GIR/lib       \
-I${P6_GTK_HOME}/p6-SOUP/lib      \
-I${P6_GTK_HOME}/p6-GSSDP/lib     \
-I${P6_GTK_HOME}/p6-GUPnP/lib     \
-I${P6_GTK_HOME}/p6-Pango/lib     \
-I${P6_GTK_HOME}/p6-GIO/lib       \
-I${P6_GTK_HOME}/p6-GDK/lib       \
-I${P6_GTK_HOME}/p6-GtkPlus/lib         \
-I${P6_GTK_HOME}/p6-GtkBuilder/lib      \
-I${P6_GTK_HOME}/p6-WebkitGTK/lib       \
-I${P6_GTK_HOME}/p6-SourceViewGTK/lib   \
-I${P6_GTK_HOME}/p6-AMTK/lib            \
-I${P6_GTK_HOME}/p6-TEPL/lib            \
-I${P6_GTK_HOME}/p6-GooCanvas/lib       \
-I${P6_GTK_HOME}/p6-Slope/lib           \
-I${P6_GTK_HOME}/p6-WNCK/lib            \
-I${P6_GTK_HOME}/p6-Clutter/lib         \
-I${P6_GTK_HOME}/p6-GtkClutter/lib      \
-I${P6_GTK_HOME}/p6-COGL/lib            \
-I${P6_GTK_HOME}/p6-GStreamer/lib       \
-I${P6_GTK_HOME}/p6-RSVG/lib            \
-I${P6_GTK_HOME}/p6-GtkSheet/lib	\
-I${P6_GTK_HOME}/p6-VTE/lib             \
-I${P6_GTK_HOME}/p6-ICal-GLib/lib       \
-Ilib -Ibin"

# Handle any extra directories in project file.
MOREI=`grep libdir .p6-gtk-project | \
cut -d= -f 2 | \
perl6 -ne '.say for .lines.split(",")'`
for a in $MOREI; do INCLUDES="-I$a $INCLUDES"; done

if [[ -z "${PARALLEL_BUILD}" ]]; then
  ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@"
else
  ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@" 2>&1 | perl -pe 's/^/$$ /'
fi
