#!/bin/bash

if [ "$1" = "--debug" ]; then
  echo "Running perl6 script in debug mode..."
  EXEC=perl6-gdb-m
  shift
elif [ "$1" = "--valgrind" ]; then
  echo "Running perl6 script in valgrind mode..."
  EXEC=perl6-valgrind-m
  shift
elif [ "$1" = "--rr" ]; then
  EXEC=rr
  shift
elif [ "$1" = "--pbuild" ]; then
  PARALLEL_BUILD=1
  EXEC=raku
  shift
else
  #echo "Running perl6 script..."
  EXEC=raku
fi

INCLUDES="\
-I${HOME}/.raku                          \
-I${P6_GTK_HOME}/cairo-p6/lib            \
-I${P6_GTK_HOME}/Method-Also/lib         \
-I${P6_GTK_HOME}/p6-GLib/lib             \
-I${P6_GTK_HOME}/p6-ATK/lib              \
-I${P6_GTK_HOME}/raku-ATSPI/lib          \
-I${P6_GTK_HOME}/p6-JSON-GLib/lib        \
-I${P6_GTK_HOME}/p6-Pango/lib            \
-I${P6_GTK_HOME}/p6-GIO/lib              \
-I${P6_GTK_HOME}/raku-GDK-Pixbuf/lib     \
-I${P6_GTK_HOME}/raku-Graphene/lib       \
-I${P6_GTK_HOME}/raku-GDK4/lib           \
-I${P6_GTK_HOME}/raku-GSK4/lib           \
-I${P6_GTK_HOME}/raku-GTK4/lib           \
-Ilib -Ibin"

# Handle any extra directories in project file.
MOREI=`grep libdir .p6-gtk-project | \
cut -d= -f 2 | \
raku -ne '.say for .lines.split(",")'`
for a in $MOREI; do INCLUDES="-I$a $INCLUDES"; done

if [[ -z "${PARALLEL_BUILD}" ]]; then
  if [ "$EXEC" = "rr" ]; then
    rr record -M -- raku --stagestats ${EXTRAS} ${INCLUDES} "$@"
  else
    ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@"
  fi
else
  ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@" 2>&1 | perl -pe 's/^/$$ /'
fi
