use v6.c;

class GTK::Builder::Base {
  my %mro = (
    'GtkCalendar' => ('GtkWidget'),
    'GtkContainer' => ('GtkWidget'),
    'GtkDrawingArea' => ('GtkWidget'),
    'GtkEntry' => ('GtkWidget'),
    'GtkFixed' => ('GtkContainer', 'GtkWidget'),
    'GtkGrid' => ('GtkContainer', 'GtkWidget'),
    'GtkHeaderBar' => ('GtkContainer', 'GtkWidget'),
    'GtkImage' => ('GtkWidget'),
    'GtkLabel' => ('GtkWidget'),
    'GtkLayout' => ('GtkContainer', 'GtkWidget'),
    'GtkLevelBar' => ('GtkWidget'),
    'GtkNotebook' => ('GtkContainer', 'GtkWidget'),
    'GtkPane' => ('GtkContainer', 'GtkWidget'),
    'GtkProgressBar' => ('GtkWidget'),
    'GtkRange' => ('GtkWidget'),
    'GtkScale' => ('GtkRange', 'GtkWidget'),
    'GtkScrollbar' => ('GtkRange', 'GtkWidget'),
    'GtkSearchEntry' => ('GtkEntry', 'GtkWidget'),
    'GtkSeparator' => ('GtkWidget'),
    'GtkSpinButton' => ('GtkEntry', 'GtkWidget'),
    'GtkSpinner' => ('GtkWidget'),
    'GtkSwitch' => ('GtkWidget'),
    'GtkTextView' => ('GtkContainer', 'GtkWidget'),
    'GtkToolItemGroup' => ('GtkContainer', 'GtkWidget'),
    'GtkToolPalette' => ('GtkContainer', 'GtkWidget'),
    'GtkToolbar' => ('GtkContainer', 'GtkWidget'),
    'GtkAccelLabel' => ('GtkLabel', 'GtkWidget'),
    'GtkBin' => ('GtkContainer', 'GtkWidget'),
    'GtkBox' => ('GtkContainer', 'GtkWidget'),
    'GtkButton' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkButtonBox' => ('GtkBox', 'GtkContainer', 'GtkWidget'),
    'GtkCellView' => ('GtkWidget'),
    'GtkColorButton' => ('GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkColorChooser' => ('GtkBox', 'GtkContainer', 'GtkWidget'),
    'GtkComboBox' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkComboBoxText' => ('GtkComboBox', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkExpander' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkFileChooserButton' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkFlowBoxChild' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkFontButton' => ('GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkFrame' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkIconView' => ('GtkContainer', 'GtkWidget'),
    'GtkInfoBar' => ('GtkBox', 'GtkContainer', 'GtkWidget'),
    'GtkLinkButton' => ('GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkListBoxRow' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkLockButton' => ('GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkMenuItem' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkMenuShell' => ('GtkContainer', 'GtkWidget'),
    'GtkOverlay' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkPopover' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkRadioMenuItem' => ('GtkMenuItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkRevealer' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkScaleButton' => ('GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkScrolledWindow' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkSearchBar' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkSeparatorMenuItem' => ('GtkMenuItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkShortcutsGroup' => ('GtkBox', 'GtkContainer', 'GtkWidget'),
    'GtkShortcutsSection' => ('GtkBox', 'GtkContainer', 'GtkWidget'),
    'GtkShortcutsShortcut' => ('GtkBox', 'GtkContainer', 'GtkWidget'),
    'GtkStackSidebar' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkStatusbar' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkToggleButton' => ('GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkToolItem' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkViewport' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkVolumeButton' => ('GtkScaleButton', 'GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkWindow' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkActionBar' => ('GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkAppButton' => ('GtkComboBox', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkAspectFrame' => ('GtkFrame', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkAssistant' => ('GtkWindow', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkCheckButton' => ('GtkToggleButton', 'GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkCheckMenuItem' => ('GtkMenuItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkDialog' => ('GtkWindow', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkFlowBox' => ('GtkContainer', 'GtkWidget'),
    'GtkListBox' => ('GtkContainer', 'GtkWidget'),
    'GtkMenu' => ('GtkMenuShell', 'GtkContainer', 'GtkWidget'),
    'GtkMenuBar' => ('GtkMenuShell', 'GtkContainer', 'GtkWidget'),
    'GtkMenuButton' => ('GtkToggleButton', 'GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkOffscreen' => ('GtkWindow', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkPlaces' => ('GtkScrolledWindow', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkRadioButton' => ('GtkCheckButton', 'GtkToggleButton', 'GtkButton', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkSeparatorToolItem' => ('GtkToolItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkStack' => ('GtkContainer', 'GtkWidget'),
    'GtkToolButton' => ('GtkToolItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkTreeView' => ('GtkContainer', 'GtkWidget'),
    'GtkMenuToolButton' => ('GtkToolButton', 'GtkToolItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkToggleToolButton' => ('GtkToolButton', 'GtkToolItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
    'GtkRadioToolButton' => ('GtkToggleToolButton', 'GtkToolButton', 'GtkToolItem', 'GtkBin', 'GtkContainer', 'GtkWidget'),
  );

  method mro {
    %mro;
  }

}
